"""add table books_authors

Revision ID: 29fe4ce6890d
Revises: a3a03e1f9d9f
Create Date: 2022-05-03 17:07:43.273719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29fe4ce6890d'
down_revision = 'a3a03e1f9d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_author',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('author_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('book_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_author_author_id'), 'books_author', ['author_id'], unique=True)
    op.create_index(op.f('ix_books_author_book_id'), 'books_author', ['book_id'], unique=True)
    op.create_index(op.f('ix_books_author_updated_at'), 'books_author', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_author_updated_at'), table_name='books_author')
    op.drop_index(op.f('ix_books_author_book_id'), table_name='books_author')
    op.drop_index(op.f('ix_books_author_author_id'), table_name='books_author')
    op.drop_table('books_author')
    # ### end Alembic commands ###
