"""add table books_categories

Revision ID: 734840390e3b
Revises: 945c81bba084
Create Date: 2022-05-03 16:56:42.228174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '734840390e3b'
down_revision = '945c81bba084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_categories',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('subcategory_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('book_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_categories_book_id'), 'books_categories', ['book_id'], unique=True)
    op.create_index(op.f('ix_books_categories_subcategory_id'), 'books_categories', ['subcategory_id'], unique=True)
    op.create_index(op.f('ix_books_categories_updated_at'), 'books_categories', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_categories_updated_at'), table_name='books_categories')
    op.drop_index(op.f('ix_books_categories_subcategory_id'), table_name='books_categories')
    op.drop_index(op.f('ix_books_categories_book_id'), table_name='books_categories')
    op.drop_table('books_categories')
    # ### end Alembic commands ###
