"""add field in table category, delete table subcategories and rename column subcategory_id to category_id

Revision ID: 7d66e77ac75d
Revises: f6472191f228
Create Date: 2022-05-05 09:53:11.850121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d66e77ac75d'
down_revision = 'f6472191f228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subcategories_category_id', table_name='subcategories')
    op.drop_index('ix_subcategories_name', table_name='subcategories')
    op.drop_index('ix_subcategories_updated_at', table_name='subcategories')
    op.drop_table('subcategories')
    op.add_column('books_categories', sa.Column('category_id', mysql.BIGINT(unsigned=True), nullable=False))
    op.drop_index('ix_books_categories_subcategory_id', table_name='books_categories')
    op.create_index(op.f('ix_books_categories_category_id'), 'books_categories', ['category_id'], unique=True)
    op.drop_column('books_categories', 'subcategory_id')
    op.add_column('categories', sa.Column('parent_id', mysql.BIGINT(unsigned=True), nullable=True))
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_column('categories', 'parent_id')
    op.add_column('books_categories', sa.Column('subcategory_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_books_categories_category_id'), table_name='books_categories')
    op.create_index('ix_books_categories_subcategory_id', 'books_categories', ['subcategory_id'], unique=False)
    op.drop_column('books_categories', 'category_id')
    op.create_table('subcategories',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('category_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_subcategories_updated_at', 'subcategories', ['updated_at'], unique=False)
    op.create_index('ix_subcategories_name', 'subcategories', ['name'], unique=False)
    op.create_index('ix_subcategories_category_id', 'subcategories', ['category_id'], unique=False)
    # ### end Alembic commands ###
