"""add table publipublishing_houses

Revision ID: e45f72210b16
Revises: 29fe4ce6890d
Create Date: 2022-05-03 17:13:40.308039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e45f72210b16'
down_revision = '29fe4ce6890d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishing_houses',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('postal_code', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('street', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('headquarters_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_houses_country'), 'publishing_houses', ['country'], unique=False)
    op.create_index(op.f('ix_publishing_houses_name'), 'publishing_houses', ['name'], unique=True)
    op.create_index(op.f('ix_publishing_houses_updated_at'), 'publishing_houses', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publishing_houses_updated_at'), table_name='publishing_houses')
    op.drop_index(op.f('ix_publishing_houses_name'), table_name='publishing_houses')
    op.drop_index(op.f('ix_publishing_houses_country'), table_name='publishing_houses')
    op.drop_table('publishing_houses')
    # ### end Alembic commands ###
