"""add table books_publishing_houses

Revision ID: f6472191f228
Revises: e45f72210b16
Create Date: 2022-05-03 17:17:46.396493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6472191f228'
down_revision = 'e45f72210b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_publishing_houses',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('publishing_house_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('book_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('publishing_year', sa.DATE(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_publishing_houses_book_id'), 'books_publishing_houses', ['book_id'], unique=True)
    op.create_index(op.f('ix_books_publishing_houses_publishing_house_id'), 'books_publishing_houses', ['publishing_house_id'], unique=True)
    op.create_index(op.f('ix_books_publishing_houses_publishing_year'), 'books_publishing_houses', ['publishing_year'], unique=True)
    op.create_index(op.f('ix_books_publishing_houses_updated_at'), 'books_publishing_houses', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_publishing_houses_updated_at'), table_name='books_publishing_houses')
    op.drop_index(op.f('ix_books_publishing_houses_publishing_year'), table_name='books_publishing_houses')
    op.drop_index(op.f('ix_books_publishing_houses_publishing_house_id'), table_name='books_publishing_houses')
    op.drop_index(op.f('ix_books_publishing_houses_book_id'), table_name='books_publishing_houses')
    op.drop_table('books_publishing_houses')
    # ### end Alembic commands ###
